---
abstract: 'A role for search engine abstraction.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
  Time::HiRes: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SearchEngine
requires:
  Data::Paginator: 0.03
  Digest::MD5: 0
  JSON::Any: 0
  JSON::XS: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Clone: 0
  MooseX::Storage: 0
  MooseX::Storage::Deferred: 0
resources:
  repository: https://github.com/gphat/data-searchengine
version: 0.29
