---
abstract: 'A role for search engine abstraction.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SearchEngine
no_index:
  directory:
    - inc
    - t
requires:
  Data::Paginator: 0.03
  Digest::MD5: 2.39
  JSON::Any: 0
  Moose: 0.89
  MooseX::Storage: 0.21
  Time::HiRes: 1.9719
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
